# https://github.com/vegasbrianc/docker-LAMP/
# docker-compose up -d
# http://localhost/phpinfo.php #environment's phpinfo()
# docker-compose ps # Verify
# docker-compose logs web # Docker logs;
# ls-la var/log/apache2 # Apache logs (via volume mount)
# docker-compose run web /var/www/html/vendor/bin/phpunit --group=foo # Do things


webserver:
  build: webserver/
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./var/log/apache2:/var/log/apache2
    - .:/var/www/html
#  command: sh /var/www/html/start.sh
    
# Wraps https://hub.docker.com/r/google/cloud-sdk/  
# Refer there for usage, adapting as needed, e.g.
# $ docker-compose run gcloud-config gcloud auth activate-service-account --key-file /home/service-account-key.json
# See https://console.cloud.google.com/apis/credentials
# $ docker-compose run gcloud-config gcloud auth login
# 
# $ docker-compose run gcloud-config gcloud app deploy /home/app.yaml --project phprioritiser
gcloud-config:
  image: google/cloud-sdk
  volumes:
# Make repository's files available to gcloud
    - .:/home/
  command: gcloud auth activate-service-account --key-file /home/service-account-key.json
#gcloud config set project phprioritiser
  